name:               demo
version:            1.0
Build-Type:         Simple
cabal-version:      >=1.10

Library
  exposed-modules:  Tokens.Android.IDIoT
                    Tokens.Android.Keystore
                    Tokens.Android.Log
                    Tokens.Android.System
                    Tokens.Android.UI
                    Tokens.Android.USB
                    Tokens.Auth
                    Tokens.Dispatch
                    Tokens.Events
                    Tokens.Sync
                    Tokens.Time
                    Tokens.UI
                    Tokens.USB
                    Tokens.XId
  ghc-options:      -O2 -Wall -fno-ignore-asserts -fwarn-tabs -fwarn-missing-import-lists -Wunused-packages
  build-depends:    asn1-encoding,
                    asn1-parse,
                    asn1-types,
                    async,
                    base,
                    base16-bytestring,
                    binary,
                    bytestring,
                    clock,
                    concurrent-loops,
                    containers,
                    cryptonite,
                    data-default,
                    deepseq,
                    entropy,
                    errors,
                    exceptions,
                    hcobs,
                    idiot,
                    idiot-cryptonite,
                    jni,
                    jvm,
                    lens,
                    memory,
                    monad-logger,
                    mtl,
                    network,
                    refined == 0.8.*,
                    safe-exceptions,
                    SafeSemaphore,
                    serialise,
                    singletons-base,
                    splitmix,
                    text,
                    time,
                    time-units,
                    transformers,
                    unix,
                    utf8-string
  hs-source-dirs:   src
  default-language: GHC2021
